name: CI

on:
  pull_request:
    branches: [ "*" ]
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt', '**/pyproject.toml', '**/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f pyproject.toml ]; then pip install .; fi

      - name: Lint (ruff, optional)
        run: |
          if python -c "import importlib; importlib.import_module('ruff')" 2>/dev/null; then ruff check .; else echo "ruff not installed, skipping"; fi

      - name: Run tests
        env:
          PYTHONPATH: .
        run: pytest --maxfail=1 --disable-warnings

      - name: Upload coverage (optional)
        if: always()
        run: |
          if [ -f .coverage ] || ls .coverage* 1> /dev/null 2>&1; then echo "coverage file exists"; else echo "no coverage configured"; fi
