name: Release zip for HACS
on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build zip
        run: |
          mkdir -p dist
          cd custom_components
          zip -r ../dist/judo_leakguard.zip judo_leakguard -x "**/__pycache__/*" "**/*.pyc"

      - name: Upload asset
        uses: softprops/action-gh-release@v1
        with:
          files: dist/judo_leakguard.zip